### ISSUE TITLE
[BUG] PATCHの修正

### ISSUE THREAD

**Issue by matumoto1234** [suzakutakumi/AizuHackServer#3]
データが文字列に変わるのをJSONなどにする

`text/html` → `application/json` に変更

```ts
// サーバには以下の形式が保存されているものとする。
type data = {
  id: string,
  value: number[]
}

// 例
{ id: 'hoge', value: [1, 2, 3] }

// このvalueを[1, 2, 3, 4]と書き換えた時、サーバのデータはこのようになってしまう。

{ id: 'hoge', value: '[1,2,3,4]' }
```

**Comment by matumoto1234** [comment]
なんか `w.Header().Set("Content-Type", "application/json")`を追加するだけでいいっぽいんよね

**Comment by matumoto1234** [comment]
全然ちがうや

**Comment by matumoto1234** [comment]
レスポンスに関することじゃなくて、書き換えに関することだから `value` を設定している部分を修正する必要がある

**Comment by suzakutakumi** [comment]
@matumoto1234 
具体的にどのメソッドとエンドポイントでエラーが起きていますか?

**Comment by matumoto1234** [comment]
PATCHメソッドだねぇ
エンドポイントって `/Data` だと思われます

`DataPatch()` の `string(body)` してるとこですね

**Comment by matumoto1234** [comment]
なおったっぽい
